name: Publish python distribution to TestPyPI and PyPI

on:
  push:

jobs:
  build-and-publish:
    name: Build and publish python distribution to TestPyPI and PyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: |
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/ .
          
